/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_books_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync_book_books__int_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookSchema */
        BookSchema: {
            /**
             * Dw Last Practiced
             * @default null
             */
            dw_last_practiced: string | null;
            /** Id */
            id: number;
            /**
             * Last Edited
             * Format: date-time
             */
            last_edited: string;
            /** Name */
            name: string;
            /** User Id */
            user_id: number;
            /**
             * Wd Last Practiced
             * @default null
             */
            wd_last_practiced: string | null;
        };
        /** ListBooksResp */
        ListBooksResp: {
            /** Books */
            books: components["schemas"]["BookSchema"][];
        };
        /**
         * PracDir
         * @enum {string}
         */
        PracDir: "wd" | "dw";
        /**
         * PracStat
         * @enum {string}
         */
        PracStat: "new" | "learning" | "waiting" | "review";
        /** PracticeSchema */
        PracticeSchema: {
            direction: components["schemas"]["PracDir"];
            /**
             * Due Counter
             * @default null
             */
            due_counter: number | null;
            /**
             * Due Dates
             * @default null
             */
            due_dates: number | null;
            /**
             * Id
             * @default null
             */
            id: number | null;
            /**
             * Last Edited
             * Format: date-time
             */
            last_edited: string;
            /**
             * Last Practiced
             * @default null
             */
            last_practiced: string | null;
            status: components["schemas"]["PracStat"];
            /** User Id */
            user_id: number;
            /** Word Id */
            word_id: number;
        };
        /** SyncBookReq */
        SyncBookReq: {
            /** Practices */
            practices: components["schemas"]["PracticeSchema"][];
        };
        /** SyncBookResp */
        SyncBookResp: {
            book: components["schemas"]["BookSchema"];
            /** Practices */
            practices: components["schemas"]["PracticeSchema"][];
            /** Words */
            words: components["schemas"]["WordSchema"][];
        };
        /** ValidationErrorModel */
        ValidationErrorModel: {
            /**
             * Error context
             * @description An optional object which contains values required to render the error message.
             * @default null
             */
            ctx: {
                [key: string]: unknown;
            } | null;
            /**
             * Input
             * @description The input provided for validation.
             */
            input: unknown;
            /**
             * Location
             * @description The error's location as a list.
             */
            loc: unknown[];
            /**
             * Message
             * @description A human readable explanation of the error.
             */
            msg: string;
            /**
             * Error Type
             * @description A computer-readable identifier of the error type.
             */
            type: string;
            /**
             * URL
             * @description The URL to further information about the error.
             * @default null
             */
            url: string | null;
        };
        /** WordSchema */
        WordSchema: {
            /** Book Id */
            book_id: number;
            /** Definition */
            definition: string;
            /** Id */
            id: number;
            /**
             * Last Edited
             * Format: date-time
             */
            last_edited: string;
            /** Sample */
            sample: string | null;
            /** Word */
            word: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_books_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBooksResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    sync_book_books__int_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBookReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncBookResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
}
