/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/ggl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_ggl_auth_ggl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_books_books_get"];
        put?: never;
        post: operations["create_book_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{bid}/words/{wid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_word_books__int_bid__words__int_wid__delete"];
        options?: never;
        head?: never;
        patch: operations["edit_word_books__int_bid__words__int_wid__patch"];
        trace?: never;
    };
    "/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_book_books__int_id__delete"];
        options?: never;
        head?: never;
        patch: operations["edit_book_books__int_id__patch"];
        trace?: never;
    };
    "/books/{id}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_book_words_books__int_id__words_get"];
        put?: never;
        post: operations["create_word_books__int_id__words_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync_book_sync__int_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookResp */
        BookResp: {
            book: components["schemas"]["BookSchema"];
        };
        /** BookSchema */
        BookSchema: {
            /**
             * Dw Last Practiced
             * Format: date-time
             */
            dw_last_practiced: string;
            /** Id */
            id: number;
            /**
             * Last Edited
             * Format: date-time
             */
            last_edited: string;
            /** Name */
            name: string;
            /** User Id */
            user_id: number;
            /**
             * Wd Last Practiced
             * Format: date-time
             */
            wd_last_practiced: string;
        };
        /** CreateBookReq */
        CreateBookReq: {
            /** Name */
            name: string;
        };
        /** CreateWordReq */
        CreateWordReq: {
            /** Definition */
            definition: string;
            /**
             * Sample
             * @default null
             */
            sample: string | null;
            /** Word */
            word: string;
        };
        /** GglAuthReq */
        GglAuthReq: {
            /** Token */
            token: string;
        };
        /** GglAuthResp */
        GglAuthResp: {
            /** Access Token */
            access_token: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** User Id */
            user_id: number;
        };
        /** ListBooksResp */
        ListBooksResp: {
            /** Books */
            books: components["schemas"]["BookSchema"][];
        };
        /** ListWordsResp */
        ListWordsResp: {
            /** Words */
            words: components["schemas"]["WordSchema"][];
        };
        /** PatchBookReq */
        PatchBookReq: {
            /** Name */
            name: string;
        };
        /** PatchWordReq */
        PatchWordReq: {
            /**
             * Definition
             * @default null
             */
            definition: string | null;
            /**
             * Sample
             * @default null
             */
            sample: string | null;
            /**
             * Word
             * @default null
             */
            word: string | null;
        };
        /**
         * PracDir
         * @enum {string}
         */
        PracDir: "wd" | "dw";
        /**
         * PracStat
         * @enum {string}
         */
        PracStat: "new" | "learning" | "waiting" | "review";
        /** PracticeSchema */
        PracticeSchema: {
            direction: components["schemas"]["PracDir"];
            /**
             * Due Counter
             * @default null
             */
            due_counter: number | null;
            /**
             * Due Dates
             * @default null
             */
            due_dates: number | null;
            /**
             * Id
             * @default null
             */
            id: number | null;
            /**
             * Last Edited
             * Format: date-time
             */
            last_edited: string;
            /**
             * Last Practiced
             * @default null
             */
            last_practiced: string | null;
            status: components["schemas"]["PracStat"];
            /** User Id */
            user_id: number;
            /** Word Id */
            word_id: number;
        };
        /** SyncBookReq */
        SyncBookReq: {
            /** Practices */
            practices: components["schemas"]["PracticeSchema"][];
        };
        /** SyncBookResp */
        SyncBookResp: {
            book: components["schemas"]["BookSchema"];
            /** Practices */
            practices: components["schemas"]["PracticeSchema"][];
            /** Words */
            words: components["schemas"]["WordSchema"][];
        };
        /** ValidationErrorModel */
        ValidationErrorModel: {
            /**
             * Error context
             * @description An optional object which contains values required to render the error message.
             * @default null
             */
            ctx: {
                [key: string]: unknown;
            } | null;
            /**
             * Input
             * @description The input provided for validation.
             */
            input: unknown;
            /**
             * Location
             * @description The error's location as a list.
             */
            loc: unknown[];
            /**
             * Message
             * @description A human readable explanation of the error.
             */
            msg: string;
            /**
             * Error Type
             * @description A computer-readable identifier of the error type.
             */
            type: string;
            /**
             * URL
             * @description The URL to further information about the error.
             * @default null
             */
            url: string | null;
        };
        /** WordResp */
        WordResp: {
            word: components["schemas"]["WordSchema"];
        };
        /** WordSchema */
        WordSchema: {
            /** Book Id */
            book_id: number;
            /** Definition */
            definition: string;
            /** Id */
            id: number;
            /**
             * Last Edited
             * Format: date-time
             */
            last_edited: string;
            /** Sample */
            sample: string;
            /** Word */
            word: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_ggl_auth_ggl_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GglAuthReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GglAuthResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    list_books_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBooksResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    create_book_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    delete_word_books__int_bid__words__int_wid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid: number;
                wid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    edit_word_books__int_bid__words__int_wid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bid: number;
                wid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchWordReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    delete_book_books__int_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    edit_book_books__int_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBookReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    list_book_words_books__int_id__words_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWordsResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    create_word_books__int_id__words_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWordReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    sync_book_sync__int_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBookReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncBookResp"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
}
